// app/layout.js
import "./globals.css";
import Navbar from './_components/Navbar';
import AppSidebar from './_components/AppSidebar';
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import { geistSans, geistMono } from "@/lib/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar:state")?.value !== "false";

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider defaultOpen={defaultOpen} className="flex">
          <AppSidebar />
          <main className="flex-1 flex flex-col min-w-0 w-full">
            <Navbar />
            <div className="flex-1 overflow-auto">
              <div className="p-6">
                {children}
              </div>
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
