import "./globals.css";
import Navbar from './_components/Navbar';
import AppSidebar from './_components/AppSidebar';
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import { geistSans, geistMono } from "@/lib/fonts";
import { ClerkProvider } from "@clerk/nextjs";
import { Provider } from "@radix-ui/react-tooltip";
import Providers from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar:state")?.value !== "false";

  return (
    <ClerkProvider>
      <html>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Providers> {/* Wraping everything with Providers component */}
            <SidebarProvider defaultOpen={defaultOpen} className="flex">
              <AppSidebar />
              <main className="flex-1 flex flex-col min-w-0 w-full">
                <Navbar />
                <div className="flex-1 overflow-auto">
                  <div className="p-6">
                    <Provider>
                      {children}
                    </Provider>
                  </div>
                </div>
              </main>
            </SidebarProvider>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}